### ISSUE TITLE
mime dependency breaking changes

### ISSUE THREAD

**Issue by valtlfelipe** [Automattic/knox#326]
[node-mime](https://github.com/broofa/node-mime) has released a new version, which requires **node>=6**. And in package.json of knox requires mim in any version `"mime": "*",`.

My enviorment uses node 4, and this just broke my application.

Please merge https://github.com/Automattic/knox/pull/325.

See the stack trace.

```
/home/ubuntu/newfleet/app/node_modules/knox/node_modules/mime/Mime.js:5
class Mime {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/newfleet/app/node_modules/knox/node_modules/mime/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/newfleet/app/node_modules/knox/lib/client.js:20:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/newfleet/app/node_modules/knox/lib/index.js:13:28)
```

**Comment by acarl005** [comment]
Similar problem. We use Node 8 but instead we get a runtime error.

```
ERROR TypeError: mime.lookup is not a function
     at /app/node_modules/knox/lib/client.js:363:28
     at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by tmoreno** [comment]
I have the same problem that @valtlfelipe

**Comment by PyroSA** [comment]
Same issue. Old 0.12.7 server got re-initialised this morning.

**Comment by PyroSA** [comment]
Thanks @valtlfelipe & @neebz
You can temporarily use their fixed version of 0.9.2 by using:
`"knox": "git://github.com/caremerge/knox.git#b1e031c209b3c17cab622a458e87728c1ee88cbd",`
In your package.json

**Comment by dwjft** [comment]
It seems this package is no longer maintained.

I have created a clone with the fix here: https://www.npmjs.com/package/knox-s3

No other changes other than pinning the `mime` version.

**Comment by manuelxaguilar** [comment]
So there's no chance of getting this fixed? I'm not using Knox directly, I'm actually using Keystone, which has Knox as a dependency itself, so I keep getting this mime.lookup error. Any suggestions if this won't get fixed?

**Comment by valtlfelipe** [comment]
@manuelxaguilar You will have to open an issue at Keystone, so they can change the `konx` dependency to use @dwjft fork for example :disappointed:

**Comment by sedge** [comment]
@manuelxaguilar You can also investigate [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) to prevent this sort of thing in the future.

**Comment by manuelxaguilar** [comment]
@valtlfelipe Yeah, I brought it up but they seem to take forever to reply... We'll see I guess.

@sedge I'm using Yarn on my project, which I believe doesn't work well with npm-shrinkwrap. I actually used ```resolutions``` to determine which version of Knox to use (I used @PyroSA fork) and it worked well on development, however it failed when deploying to Heroku because it wasn't recognizing git as a valid protocol. :/

**Comment by madsleejensen** [comment]
If you use `yarn` you can get around this issue by using https://yarnpkg.com/lang/en/docs/selective-version-resolutions/ 

`
// package.json
{
....
"resolutions": {
  "keystone/knox/mime": "1.4.0"
}
}
`

**Comment by jashmenn** [comment]
Thanks @madsleejensen - that worked for me, though I was using `knox` via the `s3-sync` package, so my `"resolutions" looked like this:

```json
    "resolutions": { "s3-sync/knox/mime": "1.4.0" } 
```

The key idea being, one needs to specify the path to `mime` via the packages they're using. (You can run `yarn why mime` to find yours.
